---
sudo: required
dist: trusty
language: generic

env:
  - PLAYBOOK=test.yml

before_install:
  - sudo apt-get update -qq

install:
  # install ansible
  - sudo pip install ansible

  # configure ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # install dependencies from meta/main.yml
  - "read dependencies < <(cat meta/main.yml  | grep 'role:' | awk '{print $3}' | tr '\n' ' '); ansible-galaxy install $dependencies"

script:
  # check syntax
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --syntax-check"

  # initial run
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --connection=local --sudo"

  # check idempotence
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --connection=local --sudo"
  
  # check that ruby is installed
  - >
    ruby -v
    | grep -q 'ruby\s[0-9]'
    && (echo 'Ruby is installed' && exit 0)
    || (echo 'Ruby is not installed' && exit 1)
