---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - ruby2.2
    - ruby2.2-dev

- name: Install Packages | gem
  gem:
    state: latest
    name: "{{ item }}"
    user_install: no
  with_items: ruby_gems
  when: ruby_gems is iterable
